apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp-main
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMouts:
    - name: sharevolume
      mountpath: /usr/share/nginx/html

  - name: myapp-sidecar
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do wget -o /var/html/index.html; echo date; sleep 15; done"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMouts:
    - name: sharevolume
      mountpath: /var/html
  volumes:
    - name: sharevolume
      emptydir: {}
    