apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp-main
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
    - name: sharedvolume
      mountPath: /usr/share/nginx/html

  - name: myapp-sidecar
    image: alpine:3.19.1
    command: ["/bin/sh"]
    args: ["-c", "apk add curl; while true; do curl -Lo /var/html/index.html https://raw.githubusercontent.com/akmanon/kubernetes_exercise/main/MulticontainerSidecarPod/index.html -s; echo date; sleep 15; done"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - name: sharedvolume
      mountPath: /var/html
  volumes:
    - name: sharedvolume
      emptyDir: {}
    