apiVersion: v1
kind: Pod
metadata:
  name: nodeaffinitypod
  labels:
    name: nodeaffinitypod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
              - ssd
          - key: db
            operator: DoesNotExist
  containers:
  - name: nodeaffinitypod
    image: httpd:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
---
apiVersion: v1
kind: Pod
metadata:
  name: nodeaffinity
  labels:
    name: nodeaffinity
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: db
            operator: DoesNotExist
  containers:
  - name: nodeaffinity
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"    