apiVersion: v1
kind: Pod
metadata:
  name: nodeaffinitypodreq
  labels:
    name: nodeaffinitypodreq
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
              - ssd
          - key: db
            operator: DoesNotExist
  containers:
  - name: nodeaffinitypodreq
    image: httpd:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
---
apiVersion: v1
kind: Pod
metadata:
  name: nodeaffinitypref
  labels:
    name: nodeaffinitypref
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: db
            operator: DoesNotExist
  containers:
  - name: nodeaffinitypref
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"    