apiVersion: batch/v1
kind: CronJob
metadata:
  name: myjob
spec:
  schedule: "2/* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            command:
            - /bin/sh
            - -c
            - date; hostname -i; echo $HOSTNAME
          restartPolicy: OnFailure