apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    app: frontend-nginx
    environment: dev
  ports:
  - port: 80
    targetPort: 80

#Imperative Way
#kubectl expose deployment/frontend --type=ClusterIP --name=frontend-svc