apiVersion: v1
kind: Pod
metadata:
  name: mysqldb
  labels:
    name: mysqldb
spec:
  containers:
  - name: mysqldb
    image: bitnami/mysql:8.0.36
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3307
