apiVersion: v1
kind: Pod
metadata:
  name: mysqldb
  labels:
    name: mysqldb
spec:
  containers:
  - name: mysqldb
    image: bitnami/mysql:8.0.36
    env:
    - name: MYSQL_DATABASE
      value:  "app_list"
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecretdb
          key: mrpass
    - name: MYSQL_USER_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecretdb
          key: mupass
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          name: mysecretdb
          key: muname
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 3306