apiVersion: v1
kind: Pod
metadata:
  name: mysqldb
  labels:
    name: mysqldb
spec:
  containers:
  - name: mysqldb
    image: mysql
    env:
    - name: MYSQL_DATABASE
      value:  "app_list"
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecretdb
          key: mrpass
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecretdb
          key: mupass
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          name: mysecretdb
          key: muname
    resources:
      limits:
        memory: "500Mi"
        cpu: "500m"
    ports:
      - containerPort: 3306