apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: prod-app-cls-1
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "svc"]
  verbs: ["get", "watch", "list"]