apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
spec:
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
        env: production
    spec:
      containers:
      - name: mysql-db
        image: mysql
        env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: mysqlpass
        resources:
          limits:
            memory: "500Mi"
            cpu: "600m"
        ports:
        - containerPort: 3306
        volumes:
          - name: mysql-pv
            persistentVolumeClaim:
              claimName: mysql-pvc