apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster
spec:
  selector:
    matchLabels:
      app: redis-cluster
      env: replica 
  serviceName: redis-cluster-svc
  replicas: 6
  template:
    metadata:
      labels:
        app: redis-cluster
        env: replica 
    spec:
      containers:
      - name: redis-cache
        image: redis:7.2.4
        command:
        - "redis-server"
        args:
        - "/conf/redis.conf"
        - "--protected-mode"
        - "no"  
        ports:
        - containerPort: 6379
          name: redis
        - containerPort: 16379
          name: redis-gossip
        volumeMounts:
        - name: conf
          mountPath: /conf
          configMap: redis-conf
        - name: data
          mountPath: /data   
        resources:
          requests:
            cpu: 100m
            memory: 100mi 
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 3Gi