apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-svc
spec:
  clusterIP: None
  selector:
    app: redis-cluster
    env: replica
  ports:
  - port: 6379
    targetPort: 6379
  - port: 16379
    targetPort: 16379
  type: ClusterIP