apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: webserver
spec:
  selector:
    matchLabels:
      app: myapp
  serviceName: nginx-svc
  replicas: 2
  template:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
          - matchExpressions:
            - key: app
              operator: In
              values: 
              - webserver
    metadata:
      labels:
        app: webserver
        env: prod
    spec:
      containers:
      - name: myapp
        image: nginx:latest
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Mi
