apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: webserver
spec:
  selector:
    matchLabels:
      app: webserver
      env: prod
  serviceName: nginx-svc
  replicas: 3
  template:
    metadata:
      labels:
        app: webserver
        env: prod
    spec:
      containers:
      - name: nginx-web
        image: nginx:latest
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app"
                operator: In
                values:
                - "nginx"
            topologyKey: kubernetes.io/hostname
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Mi